apiVersion: v1
kind: Pod
metadata:
  name: nodejs-app2
spec:
  containers:
  - name: nodejs-app2
    image: heroku/nodejs-hello-world
    ports:
    - containerPort: 3000
  - name: mysql-app
    image: mysql
    env: 
    - name: MYSQL_ROOT_PASSWORD
      value: "1234"
    ports:
    - containerPort: 3306